upload:
  oapath: "D:\\invoice\\"


spring:
#  application:
#    name: test-0.0.1
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.43.236:8848

  mail:
    host: smtp.office365.com
    from: 发送人邮箱
    username: 发送人用户名
    password: 密码
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          port: 587
          starttls:
            enable: true
            required: false
          ssl:
            enable: false
            trust: smtp.office365.com
        debug: true

http:
  a: 1
